<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cb_ink"
 *
 * Auto generated by Extension Builder 2014-12-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ink responsive HTML email',
	'description' => 'Integrates Ink responsive HTML emails (from Zurb) to TYPO3. Also includes CSS inliner and HTML to text converter.',
	'category' => 'templates',
	'author' => 'Charles Brunet',
	'author_email' => 'charles@cbrunet.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'direct_mail' => '4.0.0-5.1.99',
		),
	),
);
